// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
//const chrome = require('selenium-webdriver/chrome');
//const chrome = require('./chrimedriver');
const assert = require('assert')

describe('lol', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(new chrome.Options().headless().addArguments("--no-sandbox")).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('lol', async function() {
    await driver.get("https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal")
    await driver.manage().window().setRect({ width: 1552, height: 840 })
    await driver.executeScript("window.scrollTo(0,468)")
    await driver.findElement(By.css("div:nth-child(1) > div > .external > b")).click()
    {
      const element = await driver.findElement(By.css(".mw-wiki-logo"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    await driver.findElement(By.css("#n-mainpage-description span")).click()
  })
})
